name: moab-detect
channels:
  - conda-forge
  - defaults
dependencies:
  - cython=0.29.23=py38h23ab428_0
  - ipython_genutils=0.2.0=py_1
  - libopencv=4.5.1=py38h3a1a88b_0
  - matplotlib=3.1.3=py38_0
  - matplotlib-base=3.1.3=py38h9aa3819_0
  - numpy-base=1.19.2=py38hcfb5961_0
  - opencv=4.5.1=py38h50d1736_0
  - py-opencv=4.5.1=py38h9bb44b7_0
  - python=3.9
  - pip:
    - black==21.4b0
    - idna-ssl==1.1.0
    - ipykernel==5.3.0
    - ipython==7.15.0
    - nb-black==1.0.7
    - numpy==1.18.5
